version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: your_user # substitua pelo seu usuário do banco
      POSTGRES_PASSWORD: your_password # substitua pela sua senha do banco
      POSTGRES_DB: your_database # substitua pelo nome do seu banco de dados
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
